import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/providers/ScrollToTop";

const cairo = Cairo({
  preload: true,
  variable: "--font-cairo",
  subsets: ["latin", "arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cairo.variable} antialiased min-h-screen flex flex-col`}
      >
        <ScrollToTop />
        {/* <Header /> */}
        <main className="grow">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
